### ISSUE TITLE
Nest Model Sets, Create Model Set as Grouping of other Model Sets

### ISSUE THREAD

**Issue by ncurtiss** [multiscale-cosim/EBRAINS-cosim#13]
[Tala](https://looker.my.salesforce.com/00T2R00005XwLVK)

As Gideon, I would like to create a Model Set as a grouping of other Model Sets. For example, we could have a "base" model set of a few models that everyone in the company uses. Then the finance team could "extend" this model set with a set of models that contain sensitive financial information, etc. And if I decided to add something to the "base" model then it could propagate through all model sets without me needing to further go into each model set and add that model manually.

I would also like I would like the ability to select multiple model sets for a given role. Currently only one is allowed, as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/52678961/81761432-cb8c9680-947e-11ea-9528-ea233a913c59.png)

**Comment by w-klijn** [comment]
I doubt that this issue is for the co-simulation framework. Closing it now
