### ISSUE TITLE
Make elephant-sever integration repo public

### ISSUE THREAD

**Issue by dizcza** [multiscale-cosim/EBRAINS-cosim#20]
The link in #19 is limited to INM-6 people only.
It should be open or moved to another public place.
I'll close the issue once we do so.

**Comment by w-klijn** [comment]
@dizcza Any updates on this issue? Or should we discuss this during the Elephant meeting?

**Comment by dizcza** [comment]
It'll probably move to https://github.com/babsey/elephant-server
I'm waiting for Sebastian's confirmation.

**Comment by dizcza** [comment]
Moved to https://github.com/babsey/elephant-server - the original repo of Sebastian.
