### ISSUE TITLE
Whiteboard

### ISSUE THREAD

**Issue by mfahdaz** [multiscale-cosim/EBRAINS-cosim#42]
Aspect       | Detail
--------------|--------------
Summary       | A common place to communicate, notify, synchronize and to resolve the conflict merges.
Task Area     |
 
Assignee      | @mfahdaz @ringleschavez @sontheimer @w-klijn 
Information   | 
Prerequisites | 
Dependencies  | 

## Summary 

A common place to communicate and synchronize. One can notify here 

- the code unit (module) it is going to work on, and 
- the changes that it made in that piece of code.

The whiteboard can also be used to communicate for resolving the merge conflicts.

## Notifications

**Assignee** | **Module** | **Kanban issue | Status**

- @mfahdaz | Configuration_Manager | #37 | in-progress
- @sontheimer | translation(s) | #43 | in progress
- @ringleschavez | launcher | #39 | in progress

## Pull requests

**By** | **Description** | **Is conflict** | **Status**

- @sontheimer  | https://github.com/multiscale-cosim/TVB-NEST/pulls | No conflict | merged
- @mfahdaz  | https://github.com/multiscale-cosim/TVB-NEST/pull/ | No conflict | merged

## Backlog

- Transition state from using THREADS to using MPI as communication protocol.
- There are still undocumented functions and code snippets.
- Better Exception handling
- Directory location should be configured form configuration file

**Comment by sontheimer** [comment]
Open pull request on mpi refactoring of the translation module:
https://github.com/multiscale-cosim/TVB-NEST/pulls

**Comment by ringleschavez** [comment]
Executing nest simulation the following error is thrown:
