### ISSUE TITLE
Use-Case formalization

### ISSUE THREAD

**Issue by sontheimer** [multiscale-cosim/EBRAINS-cosim#46]
Aspect       | Detail
--------------|--------------
Summary       | 
Task Area     | 
Assignee      |
Information   | 
Prerequisites | 
Dependencies  |

**Comment by w-klijn** [comment]
Per use-case we probable need a repo with the following 'things'

Design
documentation
repostory
integration tests
template config xml

**Comment by w-klijn** [comment]
CI/CD

**Comment by w-klijn** [comment]
We should create a write-up per use-case with relevant details.
This issue needs clarification and should be completed

**Comment by w-klijn** [comment]
I just updated #64 This issue covers all of this. Closing issue because it superfluous
