### ISSUE TITLE
2.3 (splitted) Testing cosimulator TVB/NEST launcher on FZJ/CSCS infrastructure #109 #110

### ISSUE THREAD

**Issue by w-klijn** [multiscale-cosim/EBRAINS-cosim#92]
Split into #109 #110 
 CLUSTER: Prepare XML configuration files to run the Zerlaut's brain simulation by means of the workflow implemented on 
https://github.com/multiscale-cosim/TVB-NEST/blob/master/tests/test_co-sim.sh
Check the behavior of the test by scaling it up horizontally

**Comment by ringleschavez** [comment]
Split into #109 and #110
